config/routes.rb
Rails.application.routes.draw do
  resources :bancos
  resources :forma_pagos
  resources :venta
  resources :user_profiles

  
  get 'lista_departamentos/index'

	resources :lista_departamentos do
		member do
			get :delete
			get :show_user
  		end
  	end

	#get 'lista_departamentos/index'

	#resources :lista_departamentos

    resources :detalle_departamentos do
		member do
			get :delete
		end
  	end

	resources :contactos
	resources :bloqueos
	resources :usuarios

  	resources :alumnos
  	get 'home/index'
  	


  resources :departamentos do
    member do
		get :delete
		get 'listadepartamentos'
		
	  end
   end

  	resources :citations do
  		member do
			get :delete
			get :show_user
  		end
	end

	resources :proyectos do
		member do
			get :delete
			get 'listaproyectos'
		end
   end


	resources :alumnos

	
	get 'home/index'



	get 'static/aboutus'
	get 'static/contactus'
	get 'static/proyectos'
	get 'static/faq'

	get 'usuarios/index'
	get 'static/registroVta'
	get 'static/reporteDptos'

	get 'static/busquedacitas'
	get 'static/proforma'
	get 'static/separardepartamento'
	get 'static/detalledepartamento'
	get 'static/solicitarcita'
	get 'static/departamentos'
	

	root 'home#index'

	post 'static/mimetodo'


	get 'signup' => 'usuarios#new'
	get 'login' => 'sessions#new'
	post 'login' => 'sessions#create'
	delete 'logout' => 'sessions#destroy'
	

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/alumno.rb
class Alumno < ApplicationRecord
	validates :nombres, presence: {
        message: "es requerido"
    }

    validates :dni, presence: {
        message: "es requerido"
    }, length: {
        minimum: 8,
        too_short: "debe tener 8 digitos"
    }, uniqueness: {
        message: "ya esta registrado"
    }

    validates :email, presence: {
        message: "es requerido"
    }, uniqueness: {
        message: "ya esta registrado",
        case_sensitive: false
    }

    validates :edad, presence: {
        message: "es requerido"
    }
end

app/models/banco.rb
class Banco < ApplicationRecord
end

app/models/bloqueo.rb
class Bloqueo < ApplicationRecord
	validates :nombres, presence: { 
		message: "es requerido" 
	}

		validates :apellidos, presence: { 
		message: "es requerido" 
	}

    validates :dni, presence: {
        message: "es requerido"
    }, length: {
        minimum: 8,
        too_short: "debe tener 8 digitos"
    }, uniqueness: {
        message: "ya esta registrado"
    }


		validates :proyecto, presence: { 
		message: "es requerido" 
	}

		validates :departamento, presence: { 
		message: "es requerido" 
	}

		validates :voucher, presence: { 
		message: "es requerido" 
	}

		validates :tipo, presence: { 
		message: "es requerido" 
	}

		validates :monto, presence: { 
		message: "es requerido" 
	}
end

app/models/citation.rb
class Citation < ApplicationRecord

    validates :nombre, presence: {message: "es un campo requerido."}

    validates :dni, presence: {
        message: "es un campo requerido."
    }, length: {
        minimum: 8,
        too_short: "debe tener 8 digitos"
    }, uniqueness: {
        message: "ya se encuentra registrado"
    }

    validates :email,presence:{
        message: "es un campo requerido."
    }, uniqueness:{
        message: "ya se encuentra registrado",
        case_sensitive: false
    }


end

app/models/citum.rb
class Citum < ApplicationRecord
end

app/models/contacto.rb
class Contacto < ApplicationRecord
end

app/models/departamento.rb
class Departamento < ApplicationRecord	
	belongs_to :proyecto

	has_one :detalle_departamento, dependent: :destroy
	
	mount_uploader :foto, AvatarUploader
end

app/models/forma_pago.rb
class FormaPago < ApplicationRecord
end

app/models/perfil.rb
class Perfil < ApplicationRecord
end

app/models/proforma.rb
class Proforma < ApplicationRecord
	has_many :proforma_details, dependent: destroy
end

app/models/proforma_detail.rb
class ProformaDetail < ApplicationRecord
	belongs_to :proyecto
	belongs_to :proforma
end

app/models/proyecto.rb
class Proyecto < ApplicationRecord
	
	has_many :departamentos
	has_many :lista_departamentos
	
	
	has_one :detalle_departamento, through: :departamentos

	mount_uploader :avatar, AvatarUploader

end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
end

app/models/usuario.rb
class Usuario < ApplicationRecord
end

app/models/ventum.rb
class Ventum < ApplicationRecord
end

app/controllers/citations_controller.rb
class CitationsController < ApplicationController
  before_action :set_citation, only: [:show, :edit, :update, :destroy]

  # GET /citations
  # GET /citations.json
  def index
    if session[:usuario_id] == nil
      redirect_to :root

    else
        if params[:dni] || params[:nombre] || params[:agente]
          dni = params[:dni]
          nombre = params[:nombre]
          agente = params[:agente]
          @citations = Citation.where(["dni LIKE ? AND nombre LIKE ? AND agente LIKE ? ", "%#{dni}%", "%#{nombre}%", "%#{agente}%"])
        else
          @citations = Citation.all
          @citations = Citation.paginate({page: params[:page], per_page: 5})
        end
      end
  end

  # GET /citations/1
  # GET /citations/1.json
  def show
  end

  def show_user
    @citation = Citation.find(params[:id])
    
  end



  # GET /citations/new
  def new
    @citation = Citation.new
  end

  # GET /citations/1/edit
  def edit
    if session[:usuario_id] == nil
      redirect_to :root
    else
      @citation = Citation.find(params[:id])
    end

  end

  # POST /citations
  # POST /citations.json
  def create
    @citation = Citation.new(citation_params)

    #respond_to do |format|
      if @citation.save
        redirect_to(@citation)
        #format.html { redirect_to @citation, notice: 'Sus datos fueron enviados con éxito.' }
        #format.json { render :show, status: :created, location: @citation }
      else
        render 'new'
        #format.html { render :new }
        #format.json { render json: @citation.errors, status: :unprocessable_entity }
      end
    #end
  end

  # PATCH/PUT /citations/1
  # PATCH/PUT /citations/1.json
  def update
    if session[:usuario_id] == nil
      redirect_to :root
    else

          respond_to do |format|
            if @citation.update(citation_params)
              format.html { redirect_to citations_url, notice: 'Los datos de la cita fueron actualizados.' }
              format.json { render :show, status: :ok, location: @citation }
            else
              format.html { render :edit }
              format.json { render json: @citation.errors, status: :unprocessable_entity }
            end
          end
      end

  end

  # DELETE /citations/1
  # DELETE /citations/1.json
  def destroy
    if session[:usuario_id] != nil and session[:usuario_perfil] == '1'
        @citation.destroy
        respond_to do |format|
          format.html { redirect_to citations_url, notice: 'Cita eliminada' }
          format.json { head :no_content }
        end
   else
    redirect_to :root
   end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_citation
      @citation = Citation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def citation_params
      params.require(:citation).permit(:dni, :nombre, :apellido, :email, :telefono, :fechacita, :mensaje, :agente)
    end
end

app/helpers/alumnos_helper.rb
module AlumnosHelper
end

app/helpers/bancos_helper.rb
module BancosHelper
end

app/helpers/cita_helper.rb
module CitaHelper
end

app/helpers/citations_helper.rb
module CitationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/venta_helper.rb
module VentaHelper
end

app/views/citations/_form.html.erb
<%= form_with(model: citation, local: true) do |form| %>
  <% if citation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(citation.errors.count, "error") %> prohibited this citation from being saved:</h2>

      <ul>
        <% citation.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


    <div class="row">

      <div class="col-md-6">
        <div class="field">
          <%= form.label :DNI , "DNI" %>
          <%= form.text_field :dni, { :class => "form-control form-control-lg form-control-a", :placeholder => "Ingrese su DNI" } %>
        </div>
      </div>

    </div>

    <div class="row">
        <div class="col-md-6">
          <div class="field">
          <%= form.label :Nombres %>
          <%= form.text_field :nombre, { :class => "form-control form-control-lg form-control-a", :placeholder => "Ingrese sus nombres" } %>
          </div>
        </div>

      <div class="col-md-6">
      <div class="field">
        <%= form.label :Apellidos %>
        <%= form.text_field :apellido, { :class => "form-control form-control-lg form-control-a", :placeholder => "Ingrese sus apellidos" } %>
        </div>
      </div>

    </div>


    <div class="row">

      <div class="col-md-12">
        <div class="field">
          <%= form.label :Email %>
          <%= form.email_field :email, { :class => "form-control form-control-lg form-control-a", :placeholder => "Ingrese su email" } %>
        </div>
      </div>

    </div>


  <div class="row">

    <div class="col-md-6">
      <div class="field">
        <%= form.label :Telefono %>
        <%= form.text_field :telefono, { :class => "form-control form-control-lg form-control-a", :placeholder => "Ingrese su telefono" } %>
      </div>
    </div>

    <div class="col-md-6">
        <div class="field">
          <%= form.label :fechacita , "Fecha de cita" %>
          <br>
           <%= form.date_field :fechacita, :id => "datepicker", :class => "form-control form-control-lg form-control-a" %>
        </div>
    </div>
  
  </div>

     <div class="row">

      <div class="col-md-12">
          <div class="field">
            <%= form.label :mensaje, "Mensaje" %>
            <%= form.text_area :mensaje, { :class => "form-control form-control-lg form-control-a", :placeholder => "Ingrese su mensaje" } %>
          </div>
      </div>

    </div>

    
     <% if logged_in? && current_user.perfil == '1' %>
          <div class="row">
             <div class="col-md-12">
             <div class="field">
              <label for="inputAgente">Agente</label>
              <%= form.select :agente, options_from_collection_for_select(Usuario.all, :id, :nombres) , { :include_blank => "Agente a asignar" }, { :class => "form-control" } %>
            </div>
            </div>
          </div>
    <% end %>


   <div class="col-md-12 text-center">
    <div class="actions">
      <%= form.submit "Enviar Datos", :class => "btn btn-a" %>
    </div>
  </div>

<% end %>

<script>
$("#datepicker").datepicker({format: "dd/mm/yyyy"});
</script>

app/views/citations/edit.html.erb
    <section class="intro-single">
      <div class="container">
        <div class="row">
          <div class="col-md-12 col-lg-8">
            <div class="title-single-box">
              <h1 class="title-single">Edición de Citas</h1>
              <span class="color-text-a">Por favor revisar los datos y guardar la información.</span>
            </div>
          </div>
          <div class="col-md-12 col-lg-4">
            <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
              <ol class="breadcrumb">
                 <li class="breadcrumb-item active" aria-current="page">
                  <%= link_to 'Cancelar', citations_path, :class => "btn btn-light" %>
                </li>
              </ol>
            </nav>
          </div>
        </div>
      </div>
    </section>

<%= render 'form', citation: @citation %>

app/views/citations/index.html.erb
<p id="notice"><%= notice %></p>


    <section class="intro-single">
      <div class="container">
        <div class="row">
          <div class="col-md-12 col-lg-8">
            <div class="title-single-box">
              <h1 class="title-single">Listado de Citas</h1>
              <span class="color-text-a">A continuación las listas generadas a hoy.</span>
            </div>
          </div>
          <div class="col-md-12 col-lg-4">
            <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
              <ol class="breadcrumb">
                 <li class="breadcrumb-item active" aria-current="page">
                  <%= link_to 'Nueva Cita', new_citation_path , :class => "btn btn-light" %>
                </li>
              </ol>
            </nav>
          </div>
        </div>
      </div>
    </section>


 <% if logged_in? && current_user.perfil == '1' %>

    <div class="row">
      <div class="col-2">
        <%# <%= link_to 'Nuevo Proyecto', new_proyecto_path, :class=> "btn btn-warning" %>
      </div>

      <div class="col-12" align="right">    
        <%= form_tag citations_path, :method => "get", :class => "form-inline" do %>

          <div class="form-group">
            <label>Buscar por DNI:</label>
            <%= number_field_tag :dni, params[:dni], :class => "form-control mx-sm-3" %>
          </div>

          <div class="form-group">
            <label>Buscar por Nombre:</label>
            <%= text_field_tag :nombre, params[:nombre], :class => "form-control mx-sm-3" %>
          </div>

           <div class="form-group">
              <label>Buscar por Agente:</label>
              <%= text_field_tag :agente, params[:agente], :class => "form-control mx-sm-3" %>
            </div>

          
          <div class="form-group">
            <%= submit_tag 'Buscar', name: nil, :class => "btn btn-success" %>
          </div>


        <% end %>


 
        
      </div>
    </div>

<% end %>


<br><br><br>

<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th>DNI</th>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Email</th>
      <th>Telefono</th>
      <th>Fecha Cita</th>
      <th>Agente</th>
      <th>Mensaje Contacto</th>
      <th colspan="3"><center>Acciones</center></th>
    </tr>
  </thead>


  <tbody>
    <% @citations.each do |citation| %>
      <tr>
        <td><%= citation.dni %></td>
        <td><%= citation.nombre %></td>
        <td><%= citation.apellido %></td>
        <td><%= citation.email %></td>
        <td><%= citation.telefono %></td>
        <td><%= citation.fechacita %></td>
        <td><%= Usuario.select(:nombres).where("id in (" + citation.agente.to_s + ")").collect(&:nombres)[0] %></td>
        <td>
        <!-- Button trigger modal -->
          <button type="button" class="btn btn-light" data-toggle="modal" data-target="#exampleModalCenter">
            Ver Mensaje
          </button>

          <!-- Modal -->
          <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title">Mensaje</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <%= citation.mensaje %>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                </div>
              </div>
            </div>
          </div>

        </td>
        <td><%= link_to '', show_user_citation_path(citation) , class: "fa fa-info-circle" %></td> 
        <td><%= link_to '', edit_citation_path(citation) , class: "fa fa-pencil-square-o" %></td>
        <td><%= link_to '', citation, method: :delete, data: { confirm: 'Estas seguro de eliminar la cita?' }, class: "fa fa-trash" %></td>
      </tr>
    <% end %>
  </tbody>
</table>



<!-- 

<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter2">
  
</button>


<div class="modal fade" id="exampleModalCenter2" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenter2Title" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModal2LongTitle">Eliminar Cita</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Estas seguro de eliminar la cita?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
        <button type="button" class="btn btn-primary">Aceptar</button>
      </div>
    </div>
  </div>
</div>
-->

app/views/citations/new.html.erb
    <section class="intro-single">
      <div class="container">
        <div class="row">
          <div class="col-md-12 col-lg-8">
            <div class="title-single-box">
              <h1 class="title-single">Formulario de Citas</h1>
              <span class="color-text-a">Gracias por su interés, por favor a continuación puede dejarnos sus datos</span>
            </div>
          </div>
          <div class="col-md-12 col-lg-4">
            <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
              <ol class="breadcrumb">
                <li class="breadcrumb-item">
                  <a href="/">Inicio</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">
                  Generar Cita
                </li>
              </ol>
            </nav>
          </div>
        </div>
      </div>
    </section>

    <div class="container">
      <div class="row align-items-center">
            <div class="col-sm-8">
                <%= render 'form', citation: @citation %>
            </div>

            <div class="col-sm-4">
                
                <div class="icon-box section-b2">
                  <div class="icon-box-icon">
                    <span class="ion-ios-paper-plane"></span>
                  </div>

                  <div class="icon-box-content table-cell">
                    <div class="icon-box-title">
                      <h4 class="icon-title">Tambien comunicate por:</h4>
                    </div>

                    <div class="icon-box-content">
                      <p class="mb-1">Email:
                        <span class="color-a">contact@homeagency.com</span>
                      </p>
                      <p class="mb-1">Telefono
                        <span class="color-a">+51 1 4204320</span>
                      </p>
                    </div>

                  </div>

                </div>
                
                <div class="icon-box section-b2">
                  <div class="icon-box-icon">
                    <span class="ion-ios-pin"></span>
                  </div>
                  <div class="icon-box-content table-cell">
                    <div class="icon-box-title">
                      <h4 class="icon-title">Estamos en:</h4>
                    </div> 
                    <div class="icon-box-content">
                      <p class="mb-1">
                        Aparicio Robles 153, San Miguel 15088
                        <br> Lima
                      </p>
                    </div>
                  </div>
                </div>
                <div class="icon-box">
                  <div class="icon-box-icon">
                    <span class="ion-ios-redo"></span>
                  </div>
                  <div class="icon-box-content table-cell">
                    <div class="icon-box-title">
                      <h4 class="icon-title">Redes Sociales</h4>
                    </div>
                    <div class="icon-box-content">
                      <div class="socials-footer">
                        <ul class="list-inline">
                          <li class="list-inline-item">
                            <a href="https://www.facebook.com" class="link-one">
                              <i class="fa fa-facebook" aria-hidden="true"></i>
                            </a>
                          </li>
                          <li class="list-inline-item">
                            <a href="https://twitter.com" class="link-one">
                              <i class="fa fa-twitter" aria-hidden="true"></i>
                            </a>
                          </li>
                          <li class="list-inline-item">
                            <a href="https://www.instagram.com" class="link-one">
                              <i class="fa fa-instagram" aria-hidden="true"></i>
                            </a>
                          </li>
                          <li class="list-inline-item">
                            <a href="https://www.pinterest.com" class="link-one">
                              <i class="fa fa-pinterest-p" aria-hidden="true"></i>
                            </a>
                          </li>
                          <li class="list-inline-item">
                            <a href="https://dribbble.com" class="link-one">
                              <i class="fa fa-dribbble" aria-hidden="true"></i>
                            </a>
                          </li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>
              </div>





          </div>
     </div>
    </div>




              

app/views/citations/show.html.erb
<p id="notice"><%= notice %></p>


<div class="container">

    <div class="row">

      <div class="col-lg-12">

        <section class="intro-single">
            <div class="container">
              <div class="row">
                <div class="col-md-12 col-lg-8">
                  <div class="title-single-box">
                    <h1 class="title-single">Cita enviada</h1>
                    <span class="color-text-a">Un asesor lo estará contactando pronto. </span>
                  </div>
                </div>
                <div class="col-md-12 col-lg-4">
                  <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
                    <ol class="breadcrumb">
                      <li class="breadcrumb-item active" aria-current="page">
                      <%= link_to 'Ver más proyectos', "/", :class => "btn btn-light"  %>
                      </li>
                    </ol>
                  </nav>
                </div>
              </div>
            </div>
          </section>

      </div>
    </div>
  </div> 
</div>

<div class="container">
    <div class="col-md-12 section-md-t12">

                <div class="agent-info-box">
                  <div class="agent-title">
                    <div class="title-box-d">
                    <h5>Sus datos:</h5><br>
                      <h3 class="title-d"><%= @citation.nombre %> <%= @citation.apellido %></h3>
                    </div>
                  </div>

                  <div class="agent-content mb-12">
                    <p class="content-d color-text-a">
                    </p>
                    <div class="info-agents color-a">
                       <p>
                        <strong>DNI: </strong>
                        <span class="color-text-a"><%= @citation.dni %></span>
                      </p>
                      <p>
                        <strong>Telefono: </strong>
                        <span class="color-text-a"><%= @citation.telefono %></span>
                      </p>
                      <p>
                        <strong>Email: </strong>
                        <span class="color-text-a"><%= @citation.email %></span>
                      </p>
                      <p>
                        <strong>Fecha Cita: </strong>
                        <span class="color-text-a"><%= @citation.fechacita %></span>
                      </p>
                      <p>
                        <strong>Mensaje: </strong>
                        <span class="color-text-a"><%= @citation.mensaje %></span>
                      </p>
                    </div>
                  </div>
                </div>
               
                <h4>Muchas Gracias!<h4>
  </div>


<hr>
</div>

app/views/citations/show_user.html.erb
<p id="notice"><%= notice %></p>


<div class="container">

    <div class="row">

      <div class="col-lg-12">


     <section class="intro-single">
        <div class="container">
          <div class="row">
            <div class="col-md-12 col-lg-8">
              <div class="title-single-box">
                <h1 class="title-single">Detalle de cita</h1>
                <span class="color-text-a">Estado de cita: <b>Pendiente<b> </span>
              </div>
            </div>
            <div class="col-md-12 col-lg-12">
              <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item active" aria-current="page">
                    <%= link_to 'Editar', edit_citation_path(@citation), :class => "btn btn-light" %>
                  </li>
                  <li class="breadcrumb-item active" aria-current="page">
                    <%= link_to 'Atrás', citations_path, :class => "btn btn-light" %>
                  </li>
                </ol>
              </nav>
            </div>
          </div>
        </div>
    </section>

      </div>
    </div>
  </div> 



    



<br>
<div class="col-md-12 section-md-t12">
                <div class="agent-info-box">
                  <div class="agent-title">
                    <div class="title-box-d">
                      <h3 class="title-d"><%= @citation.nombre %> <%= @citation.apellido %></h3>
                    </div>
                  </div>
                  <div class="agent-content mb-12">
                    <p class="content-d color-text-a">

                    </p>
                    <div class="info-agents color-a">
                       <p>
                        <strong>DNI: </strong><br>
                        <span class="color-text-a"><%= @citation.dni %></span>
                      </p>
                      <p>
                        <strong>Telefono: </strong><br>
                        <span class="color-text-a"><%= @citation.telefono %></span>
                      </p>
                      <p>
                        <strong>Email: </strong><br>
                        <span class="color-text-a"><%= @citation.email %></span>
                      </p>
                      <p>
                        <strong>Fecha Cita: </strong><br>
                        <span class="color-text-a"><%= @citation.fechacita %></span>
                      </p>
                      <p>
                        <strong>Mensaje: </strong><br>
                        <span class="color-text-a"><%= @citation.mensaje %></span>
                      </p>
                    </div>
                  </div>
                </div>
              </div>