config/routes.rb
Rails.application.routes.draw do
  resources :bancos
  resources :forma_pagos
  resources :venta
  resources :user_profiles

  
  get 'lista_departamentos/index'

	resources :lista_departamentos do
		member do
			get :delete
			get :show_user
  		end
  	end

	#get 'lista_departamentos/index'

	#resources :lista_departamentos

    resources :detalle_departamentos do
		member do
			get :delete
		end
  	end

	resources :contactos
	resources :bloqueos
	resources :usuarios

  	resources :alumnos
  	get 'home/index'
  	


  resources :departamentos do
    member do
		get :delete
		get 'listadepartamentos'
		
	  end
   end

  	resources :citations do
  		member do
			get :delete
			get :show_user
  		end
	end

	resources :proyectos do
		member do
			get :delete
			get 'listaproyectos'
		end
   end


	resources :alumnos

	
	get 'home/index'



	get 'static/aboutus'
	get 'static/contactus'
	get 'static/proyectos'
	get 'static/faq'

	get 'usuarios/index'
	get 'static/registroVta'
	get 'static/reporteDptos'

	get 'static/busquedacitas'
	get 'static/proforma'
	get 'static/separardepartamento'
	get 'static/detalledepartamento'
	get 'static/solicitarcita'
	get 'static/departamentos'
	

	root 'home#index'

	post 'static/mimetodo'


	get 'signup' => 'usuarios#new'
	get 'login' => 'sessions#new'
	post 'login' => 'sessions#create'
	delete 'logout' => 'sessions#destroy'
	

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/departamento.rb
class Departamento < ApplicationRecord	
	belongs_to :proyecto

	has_one :detalle_departamento, dependent: :destroy
	
	mount_uploader :foto, AvatarUploader
end

app/controllers/departamentos_controller.rb
class DepartamentosController < ApplicationController
  before_action :find_proyecto
  #before_action :set_departamento, only: [:show, :edit, :update, :destroy]

  # GET /departamentos
  # GET /departamentos.json
  def index
    #obtener el  Proyecto con el id recibido
    #@proyecto = Proyecto.find(params[:proyecto_id])    
    #@departamentos = @proyecto.departamentos    

    if params[:piso] || params[:numdormitorio]
      
      @proyecto = Proyecto.find(params[:proyecto_id])
      piso = params[:piso]
      numdormitorio = params[:numdormitorio]
      @departamentos = Departamento.where(["proyecto_id = ? AND piso LIKE ? AND numdormitorio LIKE ?", params[:proyecto_id], "%#{piso}%", "%#{numdormitorio}%"])

    else
      @proyecto = Proyecto.find(params[:proyecto_id])    
      @departamentos = @proyecto.departamentos

    end

    #@departamentos = Departamento.all
  
  end

  # GET /departamentos/1
  # GET /departamentos/1.json
  def show

    @departamento = Departamento.find(params[:id])
    @detalle_departamentos = @departamento.detalle_departamento
  end

  def listadepartamentos
    @proyecto = Proyecto.find(params[:proyecto_id])    
    @departamentos = @proyecto.departamentos
    
  end

  
  def listaproyectos

    #obtener el  Proyecto con el id recibido
    @proyecto = Proyecto.find(params[:proyecto_id])
    #buscar los departamentos del author
    @departamentos = @proyecto.departamentos
     
    #@departamentos = Departamento.all
    
  end

  # GET /departamentos/new
  def new
    @departamento = Departamento.new(:proyecto_id => @proyecto.id)
    #@departamento = Departamento.new
  end


  
  def create
    #@author = Author.find(params[:author_id])
    @departamento = Departamento.create(departamento_params)
    @departamento.proyecto = @proyecto
    if @departamento.save 
      redirect_to(departamentos_path(:proyecto_id => @proyecto.id))
    else
      render 'new'
    end
  end


  # GET /departamentos/1/edit
  def edit
    @departamento = Departamento.find(params[:id])
  end

  # POST /departamentos
  # POST /departamentos.json
  
  #def create
    #@departamento = Departamento.new(departamento_params)

    #respond_to do |format|
      #if @departamento.save
        #format.html { redirect_to @departamento, notice: 'Departamento was successfully created.' }
        #format.json { render :show, status: :created, location: @departamento }
      #else
        #format.html { render :new }
        #format.json { render json: @departamento.errors, status: :unprocessable_entity }
      #end
    #end
  #end

  # PATCH/PUT /departamentos/1
  # PATCH/PUT /departamentos/1.json
  #def update
    #respond_to do |format|
      #if @departamento.update(departamento_params)
        #format.html { redirect_to @departamento, notice: 'Departamento was successfully updated.' }
        #format.json { render :show, status: :ok, location: @departamento }
      #else
        #format.html { render :edit }
        #format.json { render json: @departamento.errors, status: :unprocessable_entity }
      #end
    #end
  #end

  def update
    #@author = Author.find(params[:author_id])
    @departamento = Departamento.find(params[:id])
    if @departamento.update_attributes(departamento_params)
      redirect_to(departamento_path(@departamento, :proyecto_id => @proyecto.id))
    else
      @proyectos = []
      Proyecto.all.map { |proyecto| @proyectos.append([proyecto.nombre, proyecto.id]) }
      render('edit')
    end
  end

  def delete

  end

  # DELETE /departamentos/1
  # DELETE /departamentos/1.json
  def destroy
    @departamento = Departamento.find(params[:id])
    @departamento.destroy
    respond_to do |format|
      format.html { redirect_to(departamentos_path(:proyecto_id => @proyecto.id), notice: 'Departamento fué eliminado.') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_departamento
      @departamento = Departamento.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def departamento_params
      params.require(:departamento).permit(:numdpto, :piso, :descripcion, :precio, :area, :numdormitorio, :foto, :proyecto_id)
    end

    def find_proyecto

      @proyecto = Proyecto.find(params[:proyecto_id])
    end
end

app/helpers/departamentos_helper.rb
module DepartamentosHelper
end

app/views/departamentos/_form.html.erb
<!--Captura el Nombre del Proyecto en el Título-->

<div class="container">
  <div class="field">
    <h3><%= f.label :proyecto, "Proyecto:" %>
    <strong><%= f.object.proyecto.nombre %></strong></h3>
  </div>
  

  <div class="row">
    <div class="offset-0 col-7">

      <div class="field">
        <%= f.label :numdpto, "Número de departamento:"  %>
        <%= f.number_field :numdpto, { :class => "form-control", :required => "required" } %>
      </div>

      <div class="field">
        <%= f.label :piso, "Piso:" %>
        <%= f.number_field :piso, { :class => "form-control", :required => "required" } %>
      </div>

      <div class="field">
        <%= f.label :descripcion, "Características Generales:" %>
        <%= f.text_area :descripcion, { :class => "form-control", :rows => "6", :required => "required" } %>
      </div>

      <div class="field">
        <%= f.label :precio, "Precio $:" %>
        <%= f.text_field :precio, { :class => "form-control", :required => "required" } %>
      </div>

      <div class="field">
        <%= f.label :area, "Área metros cuadrados:" %>
        <%= f.number_field :area, { :class => "form-control", :required => "required" } %>
      </div>

      <div class="field">
        <%= f.label :numdormitorio, "Número de dormitorio:" %>
        <%= f.number_field :numdormitorio, { :class => "form-control", :required => "required" } %>
      </div>

      <div class="form-group">
        <%= f.label :foto, "Imagen:" %>
        <%= image_tag(@departamento.foto.url, style: 'height:auto;width:300px', alt: 'Foto') if @departamento.foto? %><br>
        <%= f.file_field :foto, accept:'image/*' %><br>
      </div>


 
     
      <div class="actions">
        <%= f.submit "Guardar departamento", :class => "btn btn-outline-success btn-lg active"  %>
      </div>

    </div>
  </div>

  
</div>

app/views/departamentos/edit.html.erb
<section class="intro-single">
  <div class="container">
    <div class="row">
      <div class="col-md-12 col-lg-8">
        <div class="title-single-box">
          <h1 class="title-single">Editando Departamento</h1>
          <span class="color-text-a"></span>
        </div>
      </div>
      <div class="col-md-12 col-lg-4">
        <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
          <ol class="breadcrumb">
            
            <li class="breadcrumb-item active" aria-current="page">
              <%= link_to 'Atrás', departamentos_path(@departamento,:proyecto_id => @proyecto.id), :class => "btn btn-warning" %>
            </li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</section>



<%= form_for(@departamento, :url => departamento_path(:proyecto_id => @proyecto.id)) do |f| %>

	<%= render( :partial => "form", :locals => { :f => f }) %>

<% end %>

<%= link_to 'Mostrar', departamentos_path(@departamento,:proyecto_id => @proyecto.id), :class => "btn btn-warning" %>

<%= link_to 'Atrás', departamentos_path(@departamento,:proyecto_id => @proyecto.id), :class => "btn btn-warning" %>

app/views/departamentos/index.html.erb
<section class="intro-single">
  <div class="container">
    <div class="row">
      <div class="col-md-12 col-lg-8">
        <div class="title-single-box">
          <h1 class="title-single">Listado de Departamentos</h1>
          <h4><span class="color-text-a">Proyecto: <%= @proyecto.nombre %> </span></h4>
        </div>
      </div>
      <div class="col-md-12 col-lg-4">
        <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
          <ol class="breadcrumb">

            

            <li class="breadcrumb-item">
              <%= link_to 'Regresar a Proyectos', proyectos_path, :class => "btn btn-outline-warning  active" %>
            </li>

            <% if logged_in? %>
            <li class="breadcrumb-item active" aria-current="page">
              <%= link_to('Nuevo', new_departamento_path(:proyecto_id => @proyecto.id), :class => "btn btn-warning" )  %>
            </li>
            <% end %>

          </ol>
        </nav>
      </div>
    </div>
  </div>
</section>

<p id="notice"><%= notice %></p>


<div class="row">
  <div class="col-2">
    <%# <%= link_to 'Nuevo Proyecto', new_proyecto_path, :class=> "btn btn-warning" %>
  </div>

  <div class="col-10" align="right">    
    <%# <%= form_tag departamentos_path, :method => "get", :class => "form-inline" do %>
    <%= form_tag departamentos_path, :method => "get", :class => "form-inline" do %>
      <div class="form-group">
        <label>Buscar por Nro de piso:</label>
        <%= number_field_tag :piso, params[:piso], :class => "form-control mx-sm-3" %>
      </div>
      <div class="form-group">
        <label>Buscar por Nro dormitorios:</label>
        <%= number_field_tag :numdormitorio, params[:numdormitorio], :class => "form-control mx-sm-3" %>
      </div>
      <div class="form-group">
        <%= submit_tag 'Buscar', name: nil, :class => "btn btn-success" %>
      </div>
      <%# compao oculto para guardar el id_proyecto %>
      <div>
        <%= hidden_field_tag :proyecto_id , params[:proyecto_id] %>
      </div>

    <% end %>
    
  </div>
</div>

<hr>


<% if logged_in? %>

<table class="table">
  <thead class = "table-success">
    <tr>
      <th>Numero Dpto.</th>
      <th>Piso</th>
      <th>Características</th>
      <th>Precio</th>
      <th>Area</th>
      <th>Dormitorios</th>
      <th>Proyecto</th>
      <th>Ruta de imagen</th>
      <th colspan="3"> </th>
    </tr>
  </thead>

  <tbody>
    <% @departamentos.each do |departamento| %>
      <tr>
        <td><%= departamento.numdpto %></td>
        <td><%= departamento.piso %></td>
        <td><%= departamento.descripcion %></td>
        <td><%= departamento.precio %></td>
        <td><%= departamento.area %></td>
        <td><%= departamento.numdormitorio %></td>
        <td><%= departamento.proyecto.nombre %></td>
        <td>/<%= departamento.foto_identifier %></td>
        <td><%= link_to('Mostrar', departamento_path(departamento,:proyecto_id => @proyecto.id)) %></td>
     
        <td><%= link_to('Editar', edit_departamento_path(departamento,:proyecto_id => @proyecto.id)) %></td>

        <td><%= link_to('Eliminar', departamento_path(departamento,:proyecto_id => @proyecto.id), method: :delete, data: { confirm: 'Está seguro?' }) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<hr>
<br>
<% end %>


<div class="container">

  <% n = @departamentos.count/4 %>
  <% count = 0 %>
  <% n.downto(0) do %>
    <!-- Creamos la fila -->
    <div class="row">
      <!-- Creamos maximo 3 columnas y sale -->
      <% 3.downto(0) do |i| %>
        <!-- Verificamos que el  count no sea mayor a la cantidad de proyectos para evitar error -->
        <% if count == @departamentos.count %>
          <% break %>
        <% end %>
        <!-- Obtenemos el proyectos que toca -->
        <% departamentos = @departamentos[count] %>
        <!-- Utilizamos el proyectos -->
        <div class="card">
          <%= (image_tag(departamentos.foto.url, style: 'height:220px;width:275px;', alt: 'Foto') if departamentos.foto?) %>
          <div class="card-body">
            <h4 class="card-title">Departamento: <%= departamentos.numdpto %></h4>
            <h6 class="card-text">Piso: <%= departamentos.piso %></h6>
            <h7 class="card-text">Precio $: <%= departamentos.precio %></h7>
            <p class="card-text">Dormitorios: <%= departamentos.numdormitorio %></p>
            <%= link_to('Ver Detalles', departamento_path(departamentos,:proyecto_id => @proyecto.id), :class => "btn btn-outline-success active") %>
          </div>
        </div>
        <!-- Aumentamos la posición para que en la siguiente utilice el siguiente proyectos -->
        <% count += 1 %>
      <% end %>
    </div>
  <% end %>

</div>

app/views/departamentos/listadepartamentos.html.erb
   <section class="intro-single">
      <div class="container">
        <div class="row">
          <div class="col-md-12 col-lg-8">
            <div class="title-single-box">
              <h1 class="title-single">Listado de Departamentos</h1>
              <span class="color-text-a">...</span>
            </div>
          </div>
          <div class="col-md-12 col-lg-4">
            <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
              <ol class="breadcrumb">
                <li class="breadcrumb-item">
                  <%= link_to 'Departamentos', departamentos_path(:proyecto_id => @proyecto.id), :class=> "btn btn-warning" %>
                </li>
              </ol>
            </nav>
          </div>
        </div>
      </div>
    </section>  
    
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-4">
    <%= link_to 'Nuevo Departamento', new_departamento_path(:proyecto_id => @proyecto.id), :class=> "btn btn-warning" %>
  </div>

  <div class="col-8" align="center">    
    <%= form_tag proyectos_path, :method => "get", :class => "form-inline" do %>
      <div class="form-group">
        <label>Nombre Proyecto:</label>
        <%= text_field_tag :nombre, params[:nombre], :class => "form-control mx-sm-3" %>
      </div>
      <div class="form-group">
        <label>Distrito:</label>
        <%= text_field_tag :distrito, params[:distrito], :class => "form-control mx-sm-3" %>
      </div>
      <div class="form-group">
        <%= submit_tag 'Buscar', name: nil, :class => "btn btn-success" %>
      </div>
    <% end %>
    
  </div>

</div>


    <table class="table">
      <thead>
        <tr>
          <th>Numero Dpto.</th>
          <th>Piso</th>
          <th>Características</th>
          <th>Precio</th>
          <th>Area</th>
          <th>Dormitorios</th>
          <th>Proyecto</th>
          <th>Ruta de imagen</th>
          <th>Detalles departamento</th>
          <th colspan="4">Accones</th>
        </tr>
      </thead>

      <tbody>

        <% @departamentos.each do |departamento| %>
          <tr>
            <td><%= departamento.numdpto %></td>
            <td><%= departamento.piso %></td>
            <td><%= departamento.descripcion %></td>
            <td><%= departamento.precio %></td>
            <td><%= departamento.area %></td>
            <td><%= departamento.numdormitorio %></td>
            <td><%= departamento.proyecto.nombre %></td>
            <td><%= departamento.foto_identifier %></td>
            <td><%= link_to("Ver detalles",  detalle_departamentos_path(:departamento_id => departamento.id), :class => "btn btn-outline-info btn-sm") %> </td>
            <td><%= link_to("Agregar Detalles",  new_detalle_departamento_path(:departamento_id => departamento.id)) %></td>
            <td><%= link_to('Mostrar', departamento_path(departamento,:proyecto_id => @proyecto.id)) %></td>
        
            <td><%= link_to('Editar', edit_departamento_path(departamento,:proyecto_id => @proyecto.id)) %></td>

            <td><%= link_to('Eliminar', departamento_path(departamento,:proyecto_id => @proyecto.id), method: :delete, data: { confirm: 'Está seguro?' }) %></td>
          </tr>
        <% end %>
        
      </tbody>
    </table>

app/views/departamentos/new.html.erb
    <section class="intro-single">
      <div class="container">
        <div class="row">
          <div class="col-md-12 col-lg-8">
            <div class="title-single-box">
              <h1 class="title-single">Nuevo Departamento</h1>
              <span class="color-text-a">Por favor completar los datos del departamento.</span>
            </div>
          </div>
          <div class="col-md-12 col-lg-4">
            <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
              <ol class="breadcrumb">
                <li class="breadcrumb-item active" aria-current="page">
                  <%= link_to '<< Volver', departamentos_path(@departamento,:proyecto_id => @proyecto.id), :class => "btn btn-warning" %>
                </li>
              </ol>
            </nav>
          </div>
        </div>
      </div>
    </section>


<%= form_for(@departamento, :url => departamentos_path(:proyecto_id => @proyecto.id)) do |f| %>
	
	<%= render( :partial => "form", :locals => { :f => f }) %>



<% end %>

app/views/departamentos/show.html.erb
<br><br><br><br>

<%= link_to("<< Volver a Departamentos", departamentos_path(:proyecto_id => @proyecto.id)) %>


<!-- ======= Intro Single ======= -->
<section class="intro-single">
  <div class="container">
    <div class="row">
      <div class="col-md-12 col-lg-8">
        <div class="title-single-box">
          <h1 class="title-single">Departamento : <%= @departamento.numdpto %></h1>
          <span class="color-text-a"><%= link_to("Ver Departamento",  detalle_departamentos_path(:departamento_id => @departamento.id), :class => "btn btn-outline-info") %></span>
          
        </div>
      </div>
      <div class="col-md-12 col-lg-4">
        <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
          <ol class="breadcrumb">
            
            <li class="breadcrumb-item">
              <%= link_to 'Atrás', departamentos_path(@departamento,:proyecto_id => @proyecto.id), :class => "btn btn-warning" %>
            </li>
            
          </ol>
        </nav>
      </div>
    </div>
  </div>
</section><!-- End Intro Single-->

<p id="notice"><%= notice %></p>

 


<table summary="Section form fields" class="table">

  <tr>
    <th>Piso: </th>
    <td><%= @departamento.piso %></td>
  </tr>

  <tr>
    <th>Descripcion:</th>
    <td><%= @departamento.descripcion %></td>
  </tr>

  <tr>
    <th>Precio:</th>
    <td><%= @departamento.precio %></td>
  </tr>

  <tr>
    <th>Area:</th>
    <td><%= @departamento.area %></td>
  </tr>

  <tr>
    <th>Dormitorios:</th>
    <td><%= @departamento.numdormitorio %></td>
  </tr>

  <tr>
    <th>Ruta de imagen:</th>
    <td>/<%= @departamento.foto_identifier %></td>
  </tr>

  <tr>
    <th>Imagen del Departamento:</th>
    <td>
      <%= image_tag(@departamento.foto.url, style: 'height:auto;width:500px;', alt: 'Foto') if @departamento.foto? %><br>
    </td>
  </tr>

</table>

<% if logged_in? %>

<%= link_to 'Editar departamento', edit_departamento_path(@departamento,:proyecto_id => @proyecto.id), :class => "btn btn-outline-success active" %> 

<%= link_to("Ver detalles",  detalle_departamentos_path(:departamento_id => @departamento.id), :class => "btn btn-outline-info") %>

<% end %> 