config/routes.rb
Rails.application.routes.draw do
  resources :bancos
  resources :forma_pagos
  resources :venta
  resources :user_profiles

  
  get 'lista_departamentos/index'

	resources :lista_departamentos do
		member do
			get :delete
			get :show_user
  		end
  	end

	#get 'lista_departamentos/index'

	#resources :lista_departamentos

    resources :detalle_departamentos do
		member do
			get :delete
		end
  	end

	resources :contactos
	resources :bloqueos
	resources :usuarios

  	resources :alumnos
  	get 'home/index'
  	


  resources :departamentos do
    member do
		get :delete
		get 'listadepartamentos'
		
	  end
   end

  	resources :citations do
  		member do
			get :delete
			get :show_user
  		end
	end

	resources :proyectos do
		member do
			get :delete
			get 'listaproyectos'
		end
   end


	resources :alumnos

	
	get 'home/index'



	get 'static/aboutus'
	get 'static/contactus'
	get 'static/proyectos'
	get 'static/faq'

	get 'usuarios/index'
	get 'static/registroVta'
	get 'static/reporteDptos'

	get 'static/busquedacitas'
	get 'static/proforma'
	get 'static/separardepartamento'
	get 'static/detalledepartamento'
	get 'static/solicitarcita'
	get 'static/departamentos'
	

	root 'home#index'

	post 'static/mimetodo'


	get 'signup' => 'usuarios#new'
	get 'login' => 'sessions#new'
	post 'login' => 'sessions#create'
	delete 'logout' => 'sessions#destroy'
	

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/alumno.rb
class Alumno < ApplicationRecord
	validates :nombres, presence: {
        message: "es requerido"
    }

    validates :dni, presence: {
        message: "es requerido"
    }, length: {
        minimum: 8,
        too_short: "debe tener 8 digitos"
    }, uniqueness: {
        message: "ya esta registrado"
    }

    validates :email, presence: {
        message: "es requerido"
    }, uniqueness: {
        message: "ya esta registrado",
        case_sensitive: false
    }

    validates :edad, presence: {
        message: "es requerido"
    }
end

app/models/banco.rb
class Banco < ApplicationRecord
end

app/models/bloqueo.rb
class Bloqueo < ApplicationRecord
	validates :nombres, presence: { 
		message: "es requerido" 
	}

		validates :apellidos, presence: { 
		message: "es requerido" 
	}

    validates :dni, presence: {
        message: "es requerido"
    }, length: {
        minimum: 8,
        too_short: "debe tener 8 digitos"
    }, uniqueness: {
        message: "ya esta registrado"
    }


		validates :proyecto, presence: { 
		message: "es requerido" 
	}

		validates :departamento, presence: { 
		message: "es requerido" 
	}

		validates :voucher, presence: { 
		message: "es requerido" 
	}

		validates :tipo, presence: { 
		message: "es requerido" 
	}

		validates :monto, presence: { 
		message: "es requerido" 
	}
end

app/models/citation.rb
class Citation < ApplicationRecord

    validates :nombre, presence: {message: "es un campo requerido."}

    validates :dni, presence: {
        message: "es un campo requerido."
    }, length: {
        minimum: 8,
        too_short: "debe tener 8 digitos"
    }, uniqueness: {
        message: "ya se encuentra registrado"
    }

    validates :email,presence:{
        message: "es un campo requerido."
    }, uniqueness:{
        message: "ya se encuentra registrado",
        case_sensitive: false
    }


end

app/models/citum.rb
class Citum < ApplicationRecord
end

app/models/contacto.rb
class Contacto < ApplicationRecord
end

app/models/departamento.rb
class Departamento < ApplicationRecord	
	belongs_to :proyecto

	has_one :detalle_departamento, dependent: :destroy
	
	mount_uploader :foto, AvatarUploader
end

app/models/forma_pago.rb
class FormaPago < ApplicationRecord
end

app/models/perfil.rb
class Perfil < ApplicationRecord
end

app/models/proforma.rb
class Proforma < ApplicationRecord
	has_many :proforma_details, dependent: destroy
end

app/models/proforma_detail.rb
class ProformaDetail < ApplicationRecord
	belongs_to :proyecto
	belongs_to :proforma
end

app/models/proyecto.rb
class Proyecto < ApplicationRecord
	
	has_many :departamentos
	has_many :lista_departamentos
	
	
	has_one :detalle_departamento, through: :departamentos

	mount_uploader :avatar, AvatarUploader

end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
end

app/models/usuario.rb
class Usuario < ApplicationRecord
end

app/models/ventum.rb
class Ventum < ApplicationRecord
end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController
  before_action :set_user_profile, only: [:show, :edit, :update, :destroy]

  # GET /user_profiles
  # GET /user_profiles.json
  def index
    @user_profiles = UserProfile.all
  end

  # GET /user_profiles/1
  # GET /user_profiles/1.json
  def show
  end

  # GET /user_profiles/new
  def new
    @user_profile = UserProfile.new
  end

  # GET /user_profiles/1/edit
  def edit
  end

  # POST /user_profiles
  # POST /user_profiles.json
  def create
    @user_profile = UserProfile.new(user_profile_params)

    respond_to do |format|
      if @user_profile.save
        format.html { redirect_to @user_profile, notice: 'Perfil de usuario creado.' }
        format.json { render :show, status: :created, location: @user_profile }
      else
        format.html { render :new }
        format.json { render json: @user_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_profiles/1
  # PATCH/PUT /user_profiles/1.json
  def update
    respond_to do |format|
      if @user_profile.update(user_profile_params)
        format.html { redirect_to @user_profile, notice: 'Perfil de usuario actualizado.' }
        format.json { render :show, status: :ok, location: @user_profile }
      else
        format.html { render :edit }
        format.json { render json: @user_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_profiles/1
  # DELETE /user_profiles/1.json
  def destroy
    @user_profile.destroy
    respond_to do |format|
      format.html { redirect_to user_profiles_url, notice: 'Perfil de usuario eliminado.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_profile
      @user_profile = UserProfile.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_profile_params
      params.require(:user_profile).permit(:descripcion)
    end
end

app/helpers/alumnos_helper.rb
module AlumnosHelper
end

app/helpers/bancos_helper.rb
module BancosHelper
end

app/helpers/cita_helper.rb
module CitaHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

app/helpers/venta_helper.rb
module VentaHelper
end

app/views/user_profiles/_form.html.erb
<%= form_with(model: user_profile, local: true) do |form| %>
  <% if user_profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_profile.errors.count, "error") %> prohibited this user_profile from being saved:</h2>

      <ul>
        <% user_profile.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_field :descripcion %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/user_profiles/edit.html.erb
    <section class="intro-single">
      <div class="container">
        <div class="row">
          <div class="col-md-12 col-lg-8">
            <div class="title-single-box">
              <h1 class="title-single">Editar perfil de acceso</h1>
              <span class="color-text-a">Por favor revisar los datos y actualizar. </span>
            </div>
          </div>
          <div class="col-md-12 col-lg-4">
            <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
              <ol class="breadcrumb">
                <li class="breadcrumb-item">
                  <a href="/"><button type="button" class="btn btn-light">Inicio</button></a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">
                  <%= link_to 'Usuarios', usuarios_path, :class => "btn btn-light" %>
                </li>
              </ol>
            </nav>
          </div>
        </div>
      </div>
    </section>

<%= render 'form', user_profile: @user_profile %>

<%= link_to 'Show', @user_profile %> |
<%= link_to 'Back', user_profiles_path %>

app/views/user_profiles/index.html.erb
<p id="notice"><%= notice %></p>

    <section class="intro-single">
      <div class="container">
        <div class="row">
          <div class="col-md-12 col-lg-8">
            <div class="title-single-box">
              <h1 class="title-single">Perfiles de Acceso</h1>
              <span class="color-text-a">Lista de accesos para el sistema</span>
            </div>
          </div>
          <div class="col-md-12 col-lg-4">
            <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
              <ol class="breadcrumb">
                <li class="breadcrumb-item">
                  <a href="/"><button type="button" class="btn btn-light">Inicio</button></a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">
                  <%= link_to 'Usuarios', usuarios_path, :class => "btn btn-light" %>
                </li>
              </ol>
            </nav>
          </div>
        </div>
      </div>
    </section>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_profiles.each do |user_profile| %>
      <tr>
        <td><%= user_profile.descripcion %></td>
        <td><%= link_to 'Show', user_profile %></td>
        <td><%= link_to 'Edit', edit_user_profile_path(user_profile) %></td>
        <td><%= link_to 'Destroy', user_profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Profile', new_user_profile_path %>

app/views/user_profiles/new.html.erb
    <section class="intro-single">
      <div class="container">
        <div class="row">
          <div class="col-md-12 col-lg-8">
            <div class="title-single-box">
              <h1 class="title-single">Crear un perfil de acceso</h1>
              <span class="color-text-a">...</span>
            </div>
          </div>
          <div class="col-md-12 col-lg-4">
            <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
              <ol class="breadcrumb">
                <li class="breadcrumb-item">
                  <a href="/"><button type="button" class="btn btn-light">Inicio</button></a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">
                  <%= link_to 'Usuarios', usuarios_path, :class => "btn btn-light" %>
                </li>
              </ol>
            </nav>
          </div>
        </div>
      </div>
    </section>


<%= render 'form', user_profile: @user_profile %>

<%= link_to 'Back', user_profiles_path %>

app/views/user_profiles/show.html.erb
<p id="notice"><%= notice %></p>

    <section class="intro-single">
      <div class="container">
        <div class="row">
          <div class="col-md-12 col-lg-8">
            <div class="title-single-box">
              <h1 class="title-single">Perfil de Acceso</h1>
              <span class="color-text-a">...</span>
            </div>
          </div>
          <div class="col-md-12 col-lg-4">
            <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
              <ol class="breadcrumb">
                <li class="breadcrumb-item">
                  <a href="/"><button type="button" class="btn btn-light">Inicio</button></a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">
                  <%= link_to 'Usuarios', usuarios_path, :class => "btn btn-light" %>
                </li>
              </ol>
            </nav>
          </div>
        </div>
      </div>
    </section>




<p>
  <strong>Descripcion:</strong>
  <%= @user_profile.descripcion %>
</p>

<%= link_to 'Edit', edit_user_profile_path(@user_profile) %> |
<%= link_to 'Back', user_profiles_path %>