config/routes.rb
Rails.application.routes.draw do
  resources :bancos
  resources :forma_pagos
  resources :venta
  resources :user_profiles

  
  get 'lista_departamentos/index'

	resources :lista_departamentos do
		member do
			get :delete
			get :show_user
  		end
  	end

	#get 'lista_departamentos/index'

	#resources :lista_departamentos

    resources :detalle_departamentos do
		member do
			get :delete
		end
  	end

	resources :contactos
	resources :bloqueos
	resources :usuarios

  	resources :alumnos
  	get 'home/index'
  	


  resources :departamentos do
    member do
		get :delete
		get 'listadepartamentos'
		
	  end
   end

  	resources :citations do
  		member do
			get :delete
			get :show_user
  		end
	end

	resources :proyectos do
		member do
			get :delete
			get 'listaproyectos'
		end
   end


	resources :alumnos

	
	get 'home/index'



	get 'static/aboutus'
	get 'static/contactus'
	get 'static/proyectos'
	get 'static/faq'

	get 'usuarios/index'
	get 'static/registroVta'
	get 'static/reporteDptos'

	get 'static/busquedacitas'
	get 'static/proforma'
	get 'static/separardepartamento'
	get 'static/detalledepartamento'
	get 'static/solicitarcita'
	get 'static/departamentos'
	

	root 'home#index'

	post 'static/mimetodo'


	get 'signup' => 'usuarios#new'
	get 'login' => 'sessions#new'
	post 'login' => 'sessions#create'
	delete 'logout' => 'sessions#destroy'
	

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/alumno.rb
class Alumno < ApplicationRecord
	validates :nombres, presence: {
        message: "es requerido"
    }

    validates :dni, presence: {
        message: "es requerido"
    }, length: {
        minimum: 8,
        too_short: "debe tener 8 digitos"
    }, uniqueness: {
        message: "ya esta registrado"
    }

    validates :email, presence: {
        message: "es requerido"
    }, uniqueness: {
        message: "ya esta registrado",
        case_sensitive: false
    }

    validates :edad, presence: {
        message: "es requerido"
    }
end

app/models/banco.rb
class Banco < ApplicationRecord
end

app/models/bloqueo.rb
class Bloqueo < ApplicationRecord
	validates :nombres, presence: { 
		message: "es requerido" 
	}

		validates :apellidos, presence: { 
		message: "es requerido" 
	}

    validates :dni, presence: {
        message: "es requerido"
    }, length: {
        minimum: 8,
        too_short: "debe tener 8 digitos"
    }, uniqueness: {
        message: "ya esta registrado"
    }


		validates :proyecto, presence: { 
		message: "es requerido" 
	}

		validates :departamento, presence: { 
		message: "es requerido" 
	}

		validates :voucher, presence: { 
		message: "es requerido" 
	}

		validates :tipo, presence: { 
		message: "es requerido" 
	}

		validates :monto, presence: { 
		message: "es requerido" 
	}
end

app/models/citation.rb
class Citation < ApplicationRecord

    validates :nombre, presence: {message: "es un campo requerido."}

    validates :dni, presence: {
        message: "es un campo requerido."
    }, length: {
        minimum: 8,
        too_short: "debe tener 8 digitos"
    }, uniqueness: {
        message: "ya se encuentra registrado"
    }

    validates :email,presence:{
        message: "es un campo requerido."
    }, uniqueness:{
        message: "ya se encuentra registrado",
        case_sensitive: false
    }


end

app/models/citum.rb
class Citum < ApplicationRecord
end

app/models/contacto.rb
class Contacto < ApplicationRecord
end

app/models/departamento.rb
class Departamento < ApplicationRecord	
	belongs_to :proyecto

	has_one :detalle_departamento, dependent: :destroy
	
	mount_uploader :foto, AvatarUploader
end

app/models/forma_pago.rb
class FormaPago < ApplicationRecord
end

app/models/lista_departamento.rb
class ListaDepartamento < ApplicationRecord	
	belongs_to :proyecto
	has_many :detalle_departamento
	mount_uploader :foto, AvatarUploader
end

app/models/perfil.rb
class Perfil < ApplicationRecord
end

app/models/proforma.rb
class Proforma < ApplicationRecord
	has_many :proforma_details, dependent: destroy
end

app/models/proyecto.rb
class Proyecto < ApplicationRecord
	
	has_many :departamentos
	has_many :lista_departamentos
	
	
	has_one :detalle_departamento, through: :departamentos

	mount_uploader :avatar, AvatarUploader

end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
end

app/models/usuario.rb
class Usuario < ApplicationRecord
end

app/models/ventum.rb
class Ventum < ApplicationRecord
end

app/controllers/lista_departamentos_controller.rb
class ListaDepartamentosController < ApplicationController
  before_action :set_lista_departamento, only: [:show, :edit, :update, :destroy]

  def index
  	#@lista_departamentos = Departamento.all

    if params[:piso] || params[:numdormitorio]
      piso = params[:piso]
      numdormitorio = params[:numdormitorio]
      @lista_departamentos = Departamento.where(["piso LIKE ? AND numdormitorio LIKE ?", "%#{piso}%", "%#{numdormitorio}%"])
    else
      @lista_departamentos = Departamento.all
    end

  
  	
  end

  def new
    #@departamento = Departamento.new(:proyecto_id => @proyecto.id)
    @lista_departamento = Departamento.new
  end

  def show
    @lista_departamento = Departamento.find(params[:id])

  end

  def create
    @lista_departamento = Departamento.new(lista_departamento_params)

    respond_to do |format|
      if @lista_departamento.save
        format.html { redirect_to lista_departamento_path(@lista_departamento), notice: 'Departamento guardado exitosamente.' }
        format.json { render :show, status: :created, location: @lista_departamento }
      else
        format.html { render :new }
        format.json { render json: @lista_departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @lista_departamento.update(lista_departamento_params)
        format.html { redirect_to lista_departamento_path(@lista_departamento), notice: 'Departamento guardado exitosamente.' }
        format.json { render :show, status: :ok, location: @lista_departamento }
      else
        format.html { render :edit }
        format.json { render json: @lista_departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @lista_departamento.destroy
    respond_to do |format|
      format.html { redirect_to lista_departamentos_url, notice: 'El Departamento ha sido eliminado.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lista_departamento
      @lista_departamento = Departamento.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def lista_departamento_params
      params.require(:departamento).permit(:numdpto, :piso, :descripcion, :precio, :area, :numdormitorio, :foto, :proyecto_id)
    end


end

app/controllers/listadepartamentos_controller.rb
class ListadepartamentosController < ApplicationController

  


 
end

app/helpers/alumnos_helper.rb
module AlumnosHelper
end

app/helpers/bancos_helper.rb
module BancosHelper
end

app/helpers/cita_helper.rb
module CitaHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lista_departamentos_helper.rb
module ListaDepartamentosHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/venta_helper.rb
module VentaHelper
end

app/views/lista_departamentos/_form.html.erb
  <% if @lista_departamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lista_departamento.errors.count, "error") %> prohibited this lista_departamento from being saved:</h2>

      <ul>
        <% @lista_departamento.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



 

  <div class="row">
    <div class="offset-0 col-7">

      <%# Mostrar los proyectos en un combo %>
      <div class="field">
        <%= form.label :proyecto_id %>
        <%= form.select :proyecto_id, Proyecto.all.collect {|e| [e.nombre, e.id] } , { :include_blank => "Seleccione" }, { :class => "form-control" } %>
      </div>

      <div class="field">
        <%= form.label :numdpto, "Número de departamento:"  %>
        <%= form.number_field :numdpto, { :class => "form-control", :required => "required" } %>
      </div>

      <div class="field">
        <%= form.label :piso, "Piso:" %>
        <%= form.number_field :piso, { :class => "form-control", :required => "required" } %>
      </div>

      <div class="field">
        <%= form.label :descripcion, "Características Generales:" %>
        <%= form.text_area :descripcion, { :class => "form-control", :rows => "6", :required => "required" } %>
      </div>

      <div class="field">
        <%= form.label :precio, "Precio $:" %>
        <%= form.text_field :precio, { :class => "form-control", :required => "required" } %>
      </div>

      <div class="field">
        <%= form.label :area, "Área metros cuadrados:" %>
        <%= form.number_field :area, { :class => "form-control", :required => "required" } %>
      </div>

      <div class="field">
        <%= form.label :numdormitorio, "Número de dormitorio:" %>
        <%= form.number_field :numdormitorio, { :class => "form-control", :required => "required" } %>
      </div>

      <div class="form-group">
        <%= form.label :foto, "Imagen:" %>
        <%= image_tag(@lista_departamento.foto.url, style: 'height:auto;width:300px', alt: 'Foto') if @lista_departamento.foto? %><br>
        <%= form.file_field :foto, accept:'image/*' %><br>
      </div>

      
      
      <%#
      <div class="field">
        <%= form.label :proyecto_id, "Id Proyecto:" %>
        <%#<%= form.number_field :proyecto_id, { :class => "form-control" } %>
      <%#</div>%>
     
      <div class="actions">
        <%= form.submit "Guardar departamento", :class => "btn btn-outline-success btn-lg active"  %>
      </div>

    </div>
  </div>

app/views/lista_departamentos/edit.html.erb
<section class="intro-single">
  <div class="container">
    <div class="row">
      <div class="col-md-12 col-lg-8">
        <div class="title-single-box">
          <h1 class="title-single">Departamento : <%= @lista_departamento.numdpto %></h1>
          <span class="color-text-a"><%= @lista_departamento.descripcion %></span>
        </div>
      </div>
      <div class="col-md-12 col-lg-4">
        <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
          <ol class="breadcrumb">
            
            <li class="breadcrumb-item active" aria-current="page">
              <%= link_to '<< Regresar a Departamentos', lista_departamentos_path, :class => "btn btn-warning" %>
            </li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</section>


<%= form_for(@lista_departamento, :url => lista_departamento_path()) do |form| %>
    
    <%= render( :partial => "form", :locals => { :form => form }) %>
    <%#<%= render 'form', lista_departamento: @lista_departamento %>

<% end %>


<%= link_to 'Mostrar', lista_departamento_path, :class => "btn btn-warning" %>
<%= link_to 'Cancelar', lista_departamentos_path, :class => "btn btn-warning" %>

app/views/lista_departamentos/index.html.erb
<section class="intro-single">
  <div class="container">
    <div class="row">
      <div class="col-md-12 col-lg-8">
        <div class="title-single-box">
          <h1 class="title-single">Departamentos</h1>
          <span class="color-text-a">Listado de Departamentos de todos los Proyectos</span>
        </div>
      </div>
      <div class="col-md-12 col-lg-4">
        <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              
            </li>
            <li class="breadcrumb-item active" aria-current="page">
             
            </li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</section>
    
<h3 id="notice"><%= notice %></h3><br>


<div class="row">
<% if logged_in? %>
  <div class="col-2">
    <%= link_to 'Nuevo Departamento', new_lista_departamento_path, :class=> "btn btn-warning" %>
  </div>
 <% end %>

  <div class="col-10" align="right">    
    <%# <%= form_tag departamentos_path, :method => "get", :class => "form-inline" do %>
    <%= form_tag lista_departamentos_path, :method => "get", :class => "form-inline" do %>
      <div class="form-group">
        <label>Buscar por Nro de piso:</label>
        <%= number_field_tag :piso, params[:piso], :class => "form-control mx-sm-3" %>
      </div>
      <div class="form-group">
        <label>Buscar por Nro dormitorios:</label>
        <%= number_field_tag :numdormitorio, params[:numdormitorio], :class => "form-control mx-sm-3" %>
      </div>
      <div class="form-group">
        <%= submit_tag 'Buscar', name: nil, :class => "btn btn-success" %>
      </div>
      <%# compao oculto para guardar el id_proyecto %>
      <%#<div>
        <%#<%= hidden_field_tag :proyecto_id , params[:proyecto_id] %>
      <%#</div> %>

    <% end %>
    
  </div>
</div>

<hr>

<% if logged_in? %>

<table class="table">
  <thead class="table-success" align="center">
    <tr>
      <th>Numero Dpto.</th>
      <th>Piso</th>
      <th>Características</th>
      <th>Precio</th>
      <th>Area</th>
      <th >Dormitorios</th>
      <th>Proyecto</th>
      <th>Ruta de imagen</th>
      <th colspan="3" text-align="right"> Acciones </th>
    </tr>
  </thead>

  <tbody align="center">
    <% @lista_departamentos.each do |departamento| %>
      <tr>
        <td><%= departamento.numdpto %></td>
        <td><%= departamento.piso %></td>
        <td><%= departamento.descripcion %></td>
        <td><%= departamento.precio %></td>
        <td><%= departamento.area %></td>
        <td><%= departamento.numdormitorio %></td>
        <td><%= departamento.proyecto.nombre %></td>
        <td>/<%= departamento.foto_identifier %></td>
        
        <%#departamento_path(departamento,:proyecto_id => @proyecto.id))%>
        <%#departamento_path(departamento,:proyecto_id => @proyecto.id))%>
        <td><%= link_to 'Mostrar', lista_departamento_path(departamento) %></td>
        <td><%= link_to 'Editar', edit_lista_departamento_path(departamento) %></td>
        <td><%= link_to 'Eliminar', lista_departamento_path(departamento), method: :delete, data: { confirm: 'Está seguro ?' } %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>


<hr>
<br>
<% end %> <!--END DEL CONTROL DE PERMISO-->


<% n = @lista_departamentos.count/4 %>
  <% count = 0 %>
  <% n.downto(0) do %>
    <!-- Creamos la fila -->
    <div class="row">
      <!-- Creamos maximo 3 columnas y sale -->
      <% 3.downto(0) do |i| %>
        <!-- Verificamos que el  count no sea mayor a la cantidad de proyectos para evitar error -->
        <% if count == @lista_departamentos.count %>
          <% break %>
        <% end %>
        <!-- Obtenemos el proyectos que toca -->
        <% lista_departamentos = @lista_departamentos[count] %>
        <!-- Utilizamos el proyectos -->
        <div class="card">
          <%= image_tag(lista_departamentos.foto.url, style: 'height:220px;width:275px;', alt: 'Foto') if lista_departamentos.foto? %>
          <div class="card-body">
            <h4 class="card-title">Departamento: <%= lista_departamentos.numdpto %></h4>
            <h5 class="card-text">Proyecto: <br>
              <span class="color-d"><%= lista_departamentos.proyecto.nombre %></span></h5>
            <h6 class="card-text">Piso: <%= lista_departamentos.piso %></h6>
            <h7 class="card-text">Precio $: <%= lista_departamentos.precio %></h7>
            <p class="card-text">Dormitorios: <%= lista_departamentos.numdormitorio %></p>
            <%= link_to('Ver Detalles', lista_departamento_path(lista_departamentos), :class => "btn btn-outline-success active") %>
          </div>
        </div>
        <!-- Aumentamos la posición para que en la siguiente utilice el siguiente proyectos -->
        <% count += 1 %>
      <% end %>
    </div>
  <% end %>

app/views/lista_departamentos/new.html.erb
<section class="intro-single">
    <div class="container">
    <div class="row">
        <div class="col-md-12 col-lg-8">
        <div class="title-single-box">
            <h1 class="title-single">Nuevo Departamento</h1>
            
        </div>
        </div>
        <div class="col-md-12 col-lg-4">
        <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
            <ol class="breadcrumb">

            <li class="breadcrumb-item active" aria-current="page">
                <%= link_to 'Regresar a Departamentos', lista_departamentos_path, :class => "btn btn-warning" %>
            </li>

            </ol>
        </nav>
        </div>
    </div>
    </div>
</section>


<%# <%= form_with(model: lista_departamento, local: true) do |form| %>
<%= form_for(@lista_departamento, :url => lista_departamentos_path()) do |form| %>
    
    <%= render( :partial => "form", :locals => { :form => form }) %>
    <%#<%= render 'form', lista_departamento: @lista_departamento %>

<% end %>

<%= link_to 'Cancelar', lista_departamentos_path, :class => "btn btn-warning" %>
<%# <%= render 'form', alumno: @alumno %>

app/views/lista_departamentos/show.html.erb
<!-- ======= Intro Single ======= -->
<section class="intro-single">
  <div class="container">
    <div class="row">
      <div class="col-md-12 col-lg-8">
        <div class="title-single-box">
          <h1 class="title-single">Departamento : <%= @lista_departamento.numdpto %></h1>
          <span class="color-text-a"><%= link_to("Ver Departamento",  detalle_departamentos_path(:departamento_id => @lista_departamento.id), :class => "btn btn-outline-info") %></span>
        </div>
      </div>
      <div class="col-md-12 col-lg-4">
        <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
          <ol class="breadcrumb">
            
            <li class="breadcrumb-item">
              <%#<%= link_to 'Atrás', departamentos_path(@departamento,:proyecto_id => @proyecto.id), :class => "btn btn-warning" %>
            </li>
            
          </ol>
        </nav>
      </div>
    </div>
  </div>
</section><!-- End Intro Single-->

<h3 id="notice"><%= notice %></h3><br>


<table summary="Section form fields" class="table">
  <%#Se trae el nombre de la tabla relacionada%>
  <tr>
    <th>Proyecto:</th>
    <td><%= Proyecto.select(:nombre).where("id = " + @lista_departamento.proyecto_id.to_s).collect(&:nombre)[0] %></td>
  </tr>

  <tr>
    <th>Numero Dpto:</th>
    <td><%= @lista_departamento.numdpto %></td>
  </tr>

  <tr>
    <th>Piso: </th>
    <td><%= @lista_departamento.piso %></td>
  </tr>

  <tr>
    <th>Descripcion:</th>
    <td><%= @lista_departamento.descripcion %></td>
  </tr>

  <tr>
    <th>Precio:</th>
    <td><%= @lista_departamento.precio %></td>
  </tr>

  <tr>
    <th>Area:</th>
    <td><%= @lista_departamento.area %></td>
  </tr>

  <tr>
    <th>Dormitorios:</th>
    <td><%= @lista_departamento.numdormitorio %></td>
  </tr>

  <tr>
    <th>Ruta de imagen:</th>
    <td>/<%= @lista_departamento.foto_identifier %></td>
  </tr>

  <tr>
    <th>Imagen del Proyecto:</th>
    <td>
      <%= image_tag(@lista_departamento.foto.url, style: 'height:auto;width:500px;', alt: 'Foto') if @lista_departamento.foto? %><br>
    </td>
  </tr>


</table>

<%= link_to 'Editar', edit_lista_departamento_path, :class => "btn btn-warning"  %> |
<%= link_to 'Atrás', lista_departamentos_path, :class => "btn btn-warning"  %>

<%#<%= link_to 'Editar departamento', edit_departamento_path(@departamento,:proyecto_id => @proyecto.id), :class => "btn btn-outline-success active" %> 